<?php

/**
 * Bag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    packup4me
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Bag extends BaseBag
{
    public function save(Doctrine_Connection $conn = null)
    {
        if (!$this->_get('hash')) {
            $this->_set('hash', $this->generateHash());
        }
        return parent::save($conn);
    }

    /**
     * generates a Segment unique hash based on mt_rand and base36 encoding
     * if hash unexpectedly already exists in db, it tries again
     * @return String
     */
    public function generateHash()
    {
        // generate random hash, base36 encode
        $hash = base_convert(mt_rand() . rand(0, 999), 10, 36);
        // check if unique, this is mostly unecessary
        $unique = Doctrine_Core::getTable('Bag')->findByHash($hash);
        // if hash already exists, create again
        if (count($unique) != 0) $this->generateHash();
        // we're done.
        return $hash;
    }
}
