<?php

/**
 * Bag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    packup4me
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Bag extends BaseBag
{
    public function save(Doctrine_Connection $conn = null)
    {

        if (!$this->getHash())
        {
            $this->setHash(substr(sha1(time().rand(11111, 99999)), 0, 5));
            $this->setItems($this->getPreset()->getItems());
        }



        return parent::save($conn);
    }
}
