<?php

/**
 * BagTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BagTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BagTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Bag');
    }
}