<?php

/**
 * PresetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PresetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PresetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Preset');
    }
}