<?php

/**
 * PresetItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    packup4me
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PresetItem extends BasePresetItem
{
}
