<?php

/**
 * PresetItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PresetItemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PresetItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PresetItem');
    }
}