# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:
    - "bootstrap-3.1.1-dist/css/bootstrap.min.css"
    - "bootstrap-3.1.1-dist/css/bootstrap-theme.min.css"

  javascripts:
    - "//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"
    - "../css/bootstrap-3.1.1-dist/js/bootstrap.min.js"

  has_layout:     true
  layout:         layout
